In [1]:
import numpy as np

import cv2

%matplotlib qt
import matplotlib.pyplot as plt

from PIL import Image 

import math
import numpy as np

<b> Task 2 </b>

In [29]:
image1 = cv2.imread('ss.jpg', 1)
image2 = cv2.imread('sss.jpg', 1)

plt.imshow(image2)
plt.axis('image')

point1 = plt.ginput(3, 60)
point1 = np.array(point1)

print(point1)

[[198.52839211 323.22982666]
 [303.13090257 323.22982666]
 [253.8182905   13.90526001]]


In [30]:
plt.imshow(image1)
plt.axis('image')

point2 = plt.ginput(3, 60)
point2 = np.array(point2)
print(point2)

[[302.97782258 209.83485887]
 [351.53427419 208.48606855]
 [327.25604839  61.46792339]]


In [31]:
def registerimages(image1, image2, point1, point2):
    
    matrix1 = np.arange(9)
    matrix1 = matrix1.reshape(3, 3)

    matrix1[0][0] = point1[0][0]
    matrix1[1][0] = point1[0][1]
    matrix1[2][0] = 1

    matrix1[0][1] = point1[1][0]
    matrix1[1][1] = point1[1][1]
    matrix1[2][1] = 1

    matrix1[0][2] = point1[2][0]
    matrix1[1][2] = point1[2][1]
    matrix1[2][2] = 1

    ps1 = np.linalg.pinv(matrix1)
    
    
    matrix2 = np.arange(6)
    matrix2 = matrix2.reshape(2, 3)

    matrix2[0][0] = point2[0][0]
    matrix2[1][0] = point2[0][1]

    matrix2[0][1] = point2[1][0]
    matrix2[1][1] = point2[1][1]

    matrix2[0][2] = point2[2][0]
    matrix2[1][2] = point2[2][1]

    T = np.matmul(matrix2, ps1)
    print(T)

    rows, cols, x = image1.shape

    final = cv2.warpAffine(image2, T, (cols, rows))

    for i in range(0, rows):
        for j in range(0, cols):
            if(final[i][j][0] == 0):
                final[i][j] = image1[i][j]
                
    plt.imshow(final)
    
    return final

registered = registerimages(image1, image2, point1, point2)

[[ 4.66666667e-01  2.15053763e-03  2.08905376e+02]
 [-9.52380952e-03  4.75729647e-01  5.72250384e+01]]


In [32]:
cv2.imwrite('poland_registered.jpg', registered)

True