In [140]:
import numpy as np

import cv2

%matplotlib qt
import matplotlib.pyplot as plt

from PIL import Image 

import math
import numpy as np

<b> Task 1 </b>

In [141]:
image1 = cv2.imread('mecca1.jpg', 1)
image2 = cv2.imread('mecca2.jpg', 1)

#plt.imshow(image2)
print("Click a point on the image and click the same point on the same image!")

plt.imshow(image2)
plt.axis('image')

point1 = plt.ginput(3, 30)
point1 = np.array(point1)
#(Arfa) Point 1: Left corner(the ground). Point 2: ITU logo. Point 3: Bottom right corner of parking.
print(point1)

Click a point on the image and click the same point on the same image!
[[335.60059374 180.0360813 ]
 [255.8306691  264.73007536]
 [ 43.603277   124.88650377]]


In [142]:
plt.imshow(image1)
plt.axis('image')

point2 = plt.ginput(3, 30)
point2 = np.array(point2)
print(point2)

[[ 24.91105275   9.38581868]
 [129.55823247  22.00285453]
 [138.46437543 255.41801781]]


In [143]:
def recovertransformation(image1, image2, point1, point2):
    
    matrix1 = np.arange(9)
    matrix1 = matrix1.reshape(3, 3)

    matrix1[0][0] = point1[0][0]
    matrix1[1][0] = point1[0][1]
    matrix1[2][0] = 1

    matrix1[0][1] = point1[1][0]
    matrix1[1][1] = point1[1][1]
    matrix1[2][1] = 1

    matrix1[0][2] = point1[2][0]
    matrix1[1][2] = point1[2][1]
    matrix1[2][2] = 1

    ps1 = np.linalg.pinv(matrix1)
    
    
    matrix2 = np.arange(6)
    matrix2 = matrix2.reshape(2, 3)

    matrix2[0][0] = point2[0][0]
    matrix2[1][0] = point2[0][1]

    matrix2[0][1] = point2[1][0]
    matrix2[1][1] = point2[1][1]

    matrix2[0][2] = point2[2][0]
    matrix2[1][2] = point2[2][1]

    ps2 = np.linalg.pinv(matrix2)
    
    #print(matrix1)
    #print(ps1)
    #print(matrix2)
    #print(ps2)

    
    T = np.matmul(matrix2, ps1)
    print(T)

    rows, cols, x = image1.shape

    final = cv2.warpAffine(image2, T, (cols, rows))
    plt.imshow(final)
    
    err = np.mean((image1 - final)**2)
    print("Error of Image intensity = ", err)
    
    point3 = plt.ginput(3, 30)
    point3 = np.array(point3)
    #print(point3)
    
    err1 = np.mean((point2 - point3)**2)
    print("Error of points =", err1)

    cv2.imwrite('arfa_transformed1.jpg', final)
    
    return T, final, err, err1

t, result, error1, error2 = recovertransformation(image1, image2, point1, point2)

[[ -0.53281853   0.74255378  68.83452841]
 [ -0.73745174  -0.54757308 354.60948704]]
Error of Image intensity =  48.005442307692306
Error of points = 2.341023436974018
